### ISSUE TITLE
Lots of apparmor DENIED with edge snap

### ISSUE THREAD

**Issue by pachulo** [sergiusens/telegram-snap#21]
I'm trying the edge channel of the snap (version 1.2.6 right now) and when starting the application I'm seeing a lot messages like these:

```
gen 06 10:45:47 xps kernel: audit: type=1400 audit(1515231947.544:318): apparmor="DENIED" operation="chmod" profile="snap.telegram-sergiusens.telegram" name="/var/cache/fontconfig/" pid=27936 comm="Telegram" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0

...

gen 06 10:45:47 xps audit[27936]: AVC apparmor="DENIED" operation="chmod" profile="snap.telegram-sergiusens.telegram" name="/var/cache/fontconfig/" pid=27936 comm="Telegram" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0
```
The application starts nevertheless, but after a minute or so.

**Comment by sergiusens** [comment]
I am experimenting with the desktop and desktop-legacy interfaces. That's
why.

On Jan 6, 2018 6:49 AM, "Marc" <notifications@github.com> wrote:

I'm trying the edge channel of the snap (version 1.2.6 right now) and when
starting the application I'm seeing a lot messages like these:

gen 06 10:45:47 xps kernel: audit: type=1400
audit(1515231947.544:318): apparmor="DENIED" operation="chmod"
profile="snap.telegram-sergiusens.telegram"
name="/var/cache/fontconfig/" pid=27936 comm="Telegram"
requested_mask="w" denied_mask="w" fsuid=1000 ouid=0

...

gen 06 10:45:47 xps audit[27936]: AVC apparmor="DENIED"
operation="chmod" profile="snap.telegram-sergiusens.telegram"
name="/var/cache/fontconfig/" pid=27936 comm="Telegram"
requested_mask="w" denied_mask="w" fsuid=1000 ouid=0

The application starts nevertheless, but after a minute or so.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sergiusens/telegram-snap/issues/21>, or mute the thread

**Comment by drnextgis** [comment]
Any progress on this issue?

**Comment by sergiusens** [comment]
Not really, but I don't recommend anyone touch edge
